//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Org.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int id_compra { get; set; }
        public Nullable<System.DateTime> fecha_exp { get; set; }
        public Nullable<decimal> total_fin { get; set; }
        public int id_tipo { get; set; }
        public int id_user { get; set; }
        public Nullable<int> ID_funcion { get; set; }
        public Nullable<int> ID_DETALLE { get; set; }
    
        public virtual Detalle_compra Detalle_compra { get; set; }
        public virtual Funcion Funcion { get; set; }
        public virtual Tipo_pago Tipo_pago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
