//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Org.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_compra
    {
        public int id_detalle { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public Nullable<int> ID_TIPOBOLETO { get; set; }
        public Nullable<int> Id_funcion { get; set; }
        public Nullable<int> id_compra { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Compra Compra { get; set; }
        public virtual Funcion Funcion { get; set; }
        public virtual Tipo_boleto Tipo_boleto { get; set; }
    }
}
