//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Org.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public int id_sucursal { get; set; }
        public string nombre_sucursal { get; set; }
        public int Cod_ciudad { get; set; }
        public int Cod_sala { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
