//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Org.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta_credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta_credito()
        {
            this.Tipo_pago = new HashSet<Tipo_pago>();
        }
    
        public int id_tarjeta { get; set; }
        public string numero { get; set; }
        public string ccv { get; set; }
        public Nullable<System.DateTime> fecha_ven { get; set; }
        public string coidgo_seg { get; set; }
        public Nullable<decimal> saldo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_pago> Tipo_pago { get; set; }
    }
}
